pagination

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -27,23 +27,23 @@ jobs:
     working_directory: /go/src/github.com/alexandrealvino/nf_stn
     steps:
       - checkout
-      - run:
-          # Our primary container isn't MYSQL so run a sleep command until it's ready.
-          name: Waiting for MySQL to be ready
-          command: |
-            for i in `seq 1 10`;
-            do
-            nc -z 127.0.0.1 3306 && echo Success && exit 0
-            echo -n .
-            sleep 1
-            done
-            echo Failed waiting for MySQL && exit 1
-            - run:
-                name: Install MySQL CLI; Import dummy data; run an example query
-                command: |
-                  sudo apt-get install default-mysql-client
-                  mysql -h 127.0.0.1 -u root -padmin nf_stn < database/schema.sql
-                  mysql -h 127.0.0.1 -u root -padmin --execute="SELECT * FROM nf_stn.invoices"
+#      - run:
+#          # Our primary container isn't MYSQL so run a sleep command until it's ready.
+#          name: Waiting for MySQL to be ready
+#          command: |
+#            for i in `seq 1 10`;
+#            do
+#            nc -z 127.0.0.1 3306 && echo Success && exit 0
+#            echo -n .
+#            sleep 1
+#            done
+#            echo Failed waiting for MySQL && exit 1
+#            - run:
+#                name: Install MySQL CLI; Import schema data; run an example query
+#                command: |
+#                  sudo apt-get install default-mysql-client
+#                  mysql -h 127.0.0.1 -u root -padmin nf_stn < database/schema.sql
+#                  mysql -h 127.0.0.1 -u root -padmin --execute="SELECT * FROM nf_stn.invoices"
       # specify any bash command here prefixed with `run: `
       - run: go get -v -t -d ./...
       - run: go test -v ./...
